config/routes.rb
Baoche::Application.routes.draw do
  
  resources :users do
    member do 
      get "reset_passwowrd"
    end
    collection do
      get "change_password"
    end
  end
  
  resources :home
  resources :tours
  resources :locations
  resources :orders do 
    member do 
      get "logs"
    end 
  end
  
  get "sessions/index"
  post "sessions/verify"
  get "sessions/index"
  match 'logout' =>'sessions#logout', :as => :logout 
  root :to => 'sessions#index'
  
end

app/models/ability.rb
# encoding: utf-8
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user ||= User.new # guest user (not logged in)
    if user.is?("管理员")
      can :manage, :all
    else
      can :create, Order
      can :read, Order
      can :read, Tour
      can :change_password, User, :id => user.id
    end

  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :orders, :dependent => :restrict
  validates :name, :presence => true, :uniqueness => true
end

app/models/order.rb
# encoding: utf-8
class Order < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :tour
  belongs_to :location
  has_many :order_activities
  
  after_update :logs
  
  validates_presence_of :tour_id, :location_id, :user_id, :tel, :departure_date, :link_name
  validates :num, :presence => true, :numericality => {:only_integer => true, :greater_than => 0}
  
  STATUS = {
    "待生效" => 0,
    "已生效" => 1,
    "已取消" => -1
  }
  
  def self.departure_date_option
    options = []
    0.upto(5) do |i|
      options << [Date.today + i,Date.today + i ]
    end
    options
  end
  
  private
  def logs
    self.changes.each_pair do |key, value|
      activity = OrderActivity.new
      activity.user_id = self.user_id
      activity.order_id = self.id
      activity.attr_name = key
      activity.before_change = value[0]
      activity.after_change = value[1]
      activity.save!
    end    
  end
end

app/models/order_activity.rb
class OrderActivity < ActiveRecord::Base
  belongs_to :order
  belongs_to :user
  
  default_scope where("attr_name != 'updated_at'")
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  has_many :orders, :dependent => :restrict  
  validates :name, :presence => true, :uniqueness => true
  validates :price, :presence => true, :numericality => {:only_integer => true, :greater_than => 0}
  
  private
  
end

app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
  
  validates :name, :presence => true, :uniqueness => true
  validates :tel, :presence => true, :uniqueness => true
  validates :password, :presence => true
  
  has_many :orders, :dependent => :restrict
  has_many :order_activities
  
  DEFAULT_PASSWORD = 87654321
  
  ROLES = ["管理员"]
  
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end
  
  def is?(role)
    roles.include?(role.to_s)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask || 0) & 2**ROLES.index(r)).zero?
    end
  end
  
  def roles_text
   roles.join(" ")
  end
  
end

app/controllers/application_controller.rb
# encoding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :login_required
  helper_method :current_user
  
  private
  def login_required
    if session[:user].nil?
      flash[:error] = "请登录"
      redirect_to root_path
    else
       @current_user = Thread.current[:current_user] = session[:user]   
    end
  end
  
  def current_user
    @current_user ||= User.find session[:user]
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  inherit_resources
  load_and_authorize_resource
  def index
    index!
  end
  
  def new
    new!
  end
  
  def create
    create! do |success, failure|
      success.html { redirect_to :action => :index }
      failure.html { render :action => :new }
    end
  end
  
  def edit
     @location = Location.find(params[:id])
     render :action => :new
   end

   def update
     update! do |success, failure|
       success.html { redirect_to :action => :index }
       failure.html { render :action => :new }
     end
   end
end

app/controllers/orders_controller.rb
# encoding: utf-8
class OrdersController < ApplicationController
  load_and_authorize_resource
  inherit_resources
  
  def index
    if @current_user.is?("管理员")
      @search = Order.search params[:search]
      @orders = @search.order("id desc").paginate :page => params[:page], :per_page => 20
    else
      @orders = @current_user.orders.order("id desc").paginate :page => params[:page], :per_page => 20
      render "my_orders"
    end
  end

  def new
    @tour = Tour.find(params[:tour_id])
    @order = @tour.orders.new
  end
  
  def create
    create! do |success, failure|
      success.html { redirect_to :action => :index }
      failure.html { render :action => :new }
    end
  end
  
  def edit
     @order = Order.find(params[:id])
   end

   def update
     update! do |success, failure|
       success.html { redirect_to :action => :index }
       failure.html { render :action => :new }
     end
  end
   
  def logs
     @order = Order.find(params[:id])
     @logs = @order.order_activities.order("id desc")
  end
end

app/controllers/sessions_controller.rb
# encoding: utf-8
class SessionsController < ApplicationController
  
  skip_before_filter :login_required 
  
  def index
    render :layout =>  false
  end
  
  def verify
    user_name = params[:name]
    password = params[:password]
    
    user = User.where(["name = ? and password = ?" ,user_name, password]).first
    if user.nil?
      flash[:error] = "用户名或密码错误"
      redirect_to root_path
    else
      session[:user] = user
      redirect_to orders_path
    end
  end

  def logout
    session[:user] = nil
    redirect_to root_path
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  
  inherit_resources
  load_and_authorize_resource
  def index
    @search = Tour.search params[:search]
    @tours = @search.order("id desc").paginate :page => params[:page], :per_page => 10
  end
  
  def new
    new!
  end
  
  def create
    create! do |success, failure|
      success.html { redirect_to :action => :index }
      failure.html { render :action => :new }
    end
  end
  
  def edit
     @tour = Tour.find(params[:id])
     render :action => :new
   end

   def update
     update! do |success, failure|
       success.html { redirect_to :action => :index }
       failure.html { render :action => :new }
     end
   end
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  load_and_authorize_resource
  inherit_resources
  
  def index
    index!
  end
  
  def new
    new!
  end
  
  def create
    create! do |success, failure|
      success.html { redirect_to :action => :index }
      failure.html { render :action => :new }
    end
  end
  
  def edit
    @user = User.find(params[:id])
    render :action => :new
  end

  def update
    update! do |success, failure|
      success.html { redirect_to :action => :index }
      failure.html { render :action => :new }
    end
  end
  
  def change_password
  end
  
  def reset_passwowrd
    @user = User.find(params[:id])
    @user.update_attribute(:password,User::DEFAULT_PASSWORD)
    p @user
    flash[:notice] = "密码重置成功"
    redirect_to users_path  
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Shangbanban
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    
    = csrf_meta_tags
  %body
    .topbar{'data-scrollspy' => 'scrollspy'}
      .topbar-inner
        .container
          %h3= link_to "金鹰旅行社", "#"
          %ul
            %li= link_to "线路列表", tours_path
            - if @current_user.is?("管理员")            
              %li= link_to "订单列表", orders_path
              %li= link_to "账号管理", users_path
              %li= link_to "上车地点", locations_path
            - else
              %li= link_to "我的订单", orders_path
          %ul.nav.secondary-nav
            %li= link_to @current_user.name, "#"
            %li= link_to "修改密码", change_password_users_path
            %li= link_to "退出", logout_path
    #content
      .container
        %ul.tabs
          = yield :sub_menu
        = yield

app/views/locations/index.html.haml
- content_for :sub_menu do
  %li.active= link_to "上车地点", locations_path
  %li= link_to "添加地点", new_location_path

- if flash[:notice]
  .alert-message.success= flash[:notice]
  
%h1 上车地点
%table.bordered-table.zebra-striped
  %tr
    %th 上车地点
    %th 操作
  - @locations.each do |location|
    %tr
      %td= location.name
      %td
        = link_to "修改", edit_location_path(location)
        |
        = link_to "删除", location, :method => "delete",:confirm => "确定?"

app/views/locations/new.html.haml
- content_for :sub_menu do
  %li= link_to "上车地点", locations_path
  %li.active= link_to "添加地点", new_location_path

%h1 添加或修改上车地点
= simple_form_for @location do |f|
  = f.error_notification
  = f.input :name, :label => "上车地点 :"
  = f.button :submit, "提交"

app/views/orders/_form.html.haml
= f.input :departure_date, :collection => Order.departure_date_option, :include_blank => "请选择", :label => "上车时间 :"
= f.association :location, :collection => Location.all, :include_blank => "请选择", :label => "上车地点 :"
= f.input :link_name, :label => "联系人 :"
= f.input :tel, :label => "电话:"
= f.input :num, :label => "人数:"
= f.input :remark, :label => "备注:", :as => "text", :input_html => {:rows => 5 }
= f.input :user_id, :input_html => {:value => @current_user.id }, :as => "hidden"

app/views/orders/edit.html.haml
%h1 修改订单

= simple_form_for @order do |f|
  = f.error_notification
  = f.association :tour, :collection => Tour.all, :include_blank => false, :label => "线路 :"
  = render "form", :f => f
  = f.input :status, :collection => Order::STATUS, :label => "订单状态", :include_blank => false
  = f.button :submit, "提交"

app/views/orders/index.html.haml
- content_for :sub_menu do
  %li.active= link_to "订单列表", tours_path

- if flash[:notice]
  .alert-message.success= flash[:notice]

%h1 订单列表
%table.bordered-table.zebra-striped
  %tr
    %th 订单状态
    %th 线路名称
    %th 用户名
    %th 上车地点
    %th 上车时间
    %th 人数
    %th 总价
    %th 联系人
    %th 电话
    %th 下单时间
    %th 备注
    %th 操作
  = form_for @search, :html => {:class => "search_form"} do |f|
    %tr
      %td= f.select :status_equals, Order::STATUS,{:inlcude_blank => false}, {:style => "width:70px"}
      %td= f.text_field :tour_name_contains, :class => "short_input"
      %td= f.text_field :user_name_contains, :class => "short_input"
      %td= f.text_field :location_name_contains, :class => "short_input"
      %td
      %td
      %td
      %td
      %td
      %td
      %td
      %td= f.submit "搜 索"
  - @orders.each do |order|
    %tr
      %td= Order::STATUS.rassoc(order.status)[0]
      %td= order.tour.name
      %td= order.user.name
      %td= order.location.name
      %td= order.departure_date.strftime("%Y-%m-%d")
      %td= order.num
      %td= order.num * order.tour.price
      %td= order.link_name
      %td= order.tel
      %td= order.created_at.strftime("%Y-%m-%d %H:%M:%S")
      %td= order.remark
      %td
        = link_to "查看操作记录", logs_order_path(:id => order.id)
        |
        = link_to "修改", edit_order_path(order)
        
= will_paginate @orders

app/views/orders/logs.html.haml
%table.bordered-table.zebra-striped
  %tr
    %th 名称
    %th 修改前
    %th 修改后
    %th 时间
    %th 操作人
  - @logs.each do |log|
    %tr
      %td= log.attr_name
      %td= log.before_change
      %td= log.after_change
      %td= log.created_at
      %td= log.user.name
    

app/views/orders/my_orders.haml
- content_for :sub_menu do
  %li= link_to "线路列表", tours_path
  %li.active= link_to "我的订单", orders_path

- if flash[:notice]
  .alert-message.success= flash[:notice]

%h1 我的订单
.row
  .span5.offset11 订单修改,取消 请联系139123123211
%table.bordered-table.zebra-striped
  %tr
    %th 订单状态
    %th 线路名称
    %th 上车地点
    %th 上车时间
    %th 人数
    %th 总价
    %th 联系人
    %th 电话
    %th 下单时间
    %th 备注
  - @orders.each do |order|
    %tr
      %td= Order::STATUS.rassoc(order.status)[0]
      %td= order.tour.name
      %td= order.location.name
      %td= order.departure_date.strftime("%Y-%m-%d")
      %td= order.num
      %td
      %td= order.link_name
      %td= order.tel
      %td= order.created_at.strftime("%Y-%m-%d %H:%M:%S")
      %td= order.remark
      
= will_paginate @orders
      

app/views/orders/new.html.haml
%h1= "新建订单  #{@tour.name}"

= simple_form_for @order do |f|
  = f.error_notification
  = render "form", :f => f
  = f.input :tour_id, :input_html => {:value => @tour.id }, :as => "hidden"
  = f.button :submit, "提交"

app/views/tours/index.html.haml
- content_for :sub_menu do
  %li.active= link_to "线路列表", tours_path
  - if can? :new, @tour
    %li= link_to "添加线路", new_tour_path
    
- if flash[:notice]
  .alert-message.success= flash[:notice]
  
%h1 线路列表
%table.bordered-table.zebra-striped
  %tr
    %th 线路名称
    %th{:style => "width:200px;"} 价格
    %th{:style => "width:200px;"} 操作
  - @tours.each do |tour|
    %tr
      %td= tour.name
      %td= tour.price
      %td
        = link_to "下单", new_order_path(:tour_id => tour.id)
        - if can? :update, @tour
          |
          = link_to "修改", edit_tour_path(tour)
          |
          = link_to "删除", tour, :method => "delete",:confirm => "确定?"

app/views/tours/new.html.haml
- content_for :sub_menu do
  %li= link_to "线路列表", tours_path
  %li.active= link_to "添加线路", new_tour_path

%h1 添加或修改线路
= simple_form_for @tour do |f|
  = f.error_notification
  = f.input :name, :label => "线路名称:"
  = f.input :price, :label => "价格:"
  = f.button :submit, "提交"

app/views/users/change_password.html.haml
%h1 添加或修改用户
= simple_form_for @current_user do |f|
  = f.error_notification
  = f.input :password, :label => "新密码", :input_html => { :value => nil}
  = f.button :submit, "提交"

app/views/users/index.html.haml
- content_for :sub_menu do
  %li.active= link_to "用户列表", users_path
  %li= link_to "添加新用户", new_user_path

- if flash[:notice]
  .alert-message.success= flash[:notice]

%table.bordered-table.zebra-striped
  %tr
    %th 用户姓名
    %th 角色(普通员工/管理员)
    %th 电话
    %th 操作
  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.roles_text.blank? ? "普通员工" : user.roles_text
      %td= user.tel
      %td
        = link_to "重置密码", reset_passwowrd_user_path(:id => user.id), :confirm => "确定?"
        |
        = link_to "修改", edit_user_path(user)
        |
        = link_to "删除", user, :method => "delete",:confirm => "确定?"

app/views/users/new.html.haml
- content_for :sub_menu do
  %li= link_to "用户列表", users_path
  %li.active= link_to "添加新用户", new_user_path


%h1 添加或修改用户
= simple_form_for @user do |f|
  = f.error_notification
  - if @user.new_record?
    .initial_pwd= "初始密码: #{User::DEFAULT_PASSWORD}"
    = f.input :password, :input_html => { :value => User::DEFAULT_PASSWORD }, :as => :hidden
  = f.input :name, :label => "姓名"
  = f.input :tel, :label => "电话"
  = f.input :roles, :collection => User::ROLES, :as => :check_boxes, :label => "权限"
  = f.button :submit, "提交"